### ISSUE TITLE
Mejoras  > Vistas desde un celular

### ISSUE THREAD

**Issue by Jaime-Mora** [Javier-Barreto/TodoList#12]
**Los apartados que contienen las _Tasks_ y _Completed Tasks_ no son responsivos desde la perspectiva de un Celular**
No se alcanza a observar el btn  **Done** en el apartado de **Tasks**, como consecuencia no se puede accionar para marcar cuando el usuario finaliza su tarea
![WhatsApp Image 2024-04-09 at 12 45 14 PM](https://github.com/Javier-Barreto/TodoList/assets/79118092/04ec3720-a3b0-4c23-afc8-19f7801c6aac)

**Comment by Javier-Barreto** [comment]
Ya se resolvio este issue, lo voy a cerrar
