### ISSUE TITLE
Oops!

### ISSUE THREAD

**Issue by Jaime-Mora** [Javier-Barreto/TodoList#8]
Fallo al darle Clic al botón **LOGIN**
![Captura de pantalla 2024-04-08 104529](https://github.com/Javier-Barreto/TodoList/assets/79118092/11e8ed7f-35af-4753-a63f-8b00f1109166)

![Captura de pantalla 2024-04-08 104958](https://github.com/Javier-Barreto/TodoList/assets/79118092/a30ffb8a-31da-4dc3-a696-fce92a2b95ec)

**Comment by Jaime-Mora** [comment]
![Captura de pantalla 2024-04-08 110251](https://github.com/Javier-Barreto/TodoList/assets/79118092/10a61572-4dbf-4ba4-97e0-f2eb476c6e4f)
Falla también en otros browser

**Comment by Jaime-Mora** [comment]
![Captura de pantalla 2024-04-09 121642](https://github.com/Javier-Barreto/TodoList/assets/79118092/59d93d42-2e1d-4442-a79c-35674643d282)

**Comment by Javier-Barreto** [comment]
Currently working properly, no oops issue anymore
